### PR TITLE
added GI introspection to RygelRendererGst

### PR DESCRIPTION
**Pull request by tripzero**

### CODE REVIEW

**Comment by phako** [comment]
I tried to merge this but I get a vala compiler error:

rygel-playbin-player.vala:33.1-33.44: warning: Namespace Playbin does not have a GIR namespace and version annotation

**Comment by tripzero** [comment]
That's just a warning.

**Comment by phako** [comment]
Yeah, I remember, valac has issues with GIR and nested namespaces.

**Comment by phako** [comment]
Pushed with minor modification.

**Comment by tripzero** [comment]
> > Pushed with minor modification

Not sure what you mean by pushed?  Is this merged?

**Comment by tripzero** [comment]
I pushed another commit that adds an example gst renderer python test script.

**Comment by phako** [comment]
Pushed it to the main repository. See https://github.com/GNOME/rygel/commit/b262e4a553606699adb581dfc8feae4d99636135 here. I don't have admin rights on this repository yet so I can't close the pull request.

**Comment by phako** [comment]
The Example does not have any license. Would you mind putting it under the 2-clause BSD license as the rest of the GI examples?

**Comment by tripzero** [comment]
Oops.  Yes.  I'll fix that.

**Comment by fredoche** [comment]
Any news about this feature ?  Or was it integrated somehow else ?

**Comment by phako** [comment]
The introspection itself is integrated, the example isn't.

**Comment by gnomesysadmins** [comment]
Thank you for contributing to rygel!

rygel uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
